services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "local_password"
      POSTGRES_DB: "my_database"
    ports:
      - "5432:5432"
